blogApp/urls.py
from django.urls import path
from .views import IndexView, BlogView, ContactView, BlogDetail

app_name = 'blogApp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('blogs/', BlogView.as_view(), name='blogs'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('blogdetail/<slug>/', BlogDetail.as_view(), name='blogdetail')
]

blogProj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = 'EtihasikDunia Admin'
admin.site.site_title = 'EtihasikDunia Admin'
# admin.site.site_url = 'http://coffeehouse.com/'
admin.site.index_title = 'EtihasikDunia Administration'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('blogApp.urls', namespace='blogApp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogApp/models.py
from django.db import models
from datetime import datetime
from django.shortcuts import reverse
from django.contrib.auth.models import User

# import smtplib 

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	avatar = models.ImageField(upload_to='Profile')

	def __str__(self):
		return self.user.username


class Blog(models.Model):
	title = models.CharField(max_length=800)
	brief = models.CharField(max_length=2500)
	body = models.TextField()
	image = models.ImageField(upload_to='Blog_Img', null=True, blank=True)
	slug = models.CharField(max_length=100, unique=True)
	date = models.DateTimeField(default=datetime.now)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("blogApp:blogdetail", kwargs={'slug':self.slug})

	class Meta:
		ordering = ['-date']


class Contact(models.Model):
	name = models.CharField(max_length=200)
	email = models.EmailField(max_length=300)
	phone = models.IntegerField()
	message = models.TextField()

	def __str__(self):
		return self.name

class Subscriber(models.Model):
	email=models.EmailField(max_length=300)

	def __str__(self):
		return f"{self.email}"


class Crousal(models.Model):
	name = models.CharField(max_length=100)
	image = models.ImageField(upload_to='Crousal')
	date = models.DateTimeField(default=datetime.now)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['-date']

blogApp/forms.py
from django import forms

class ContactForm(forms.Form):
	name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter Your Name','class':'form-control'}))
	email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Enter Your Email','class':'form-control'}))
	phone = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder': 'Enter Your Phone Number','class':'form-control'}))
	message = forms.CharField(label='',widget=forms.Textarea(attrs={'rows':4, 'cols':15,'placeholder': 'Enter your message','class':'form-control'}))


class SubscribeForm(forms.Form):
	email = email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Enter Your Email','class':'form-control searchInput'}))

blogApp/views.py
from django.shortcuts import render, redirect
from django.views.generic import View, ListView, DetailView
from .models import Blog, Contact, Subscriber, Crousal, UserProfile
from .forms import ContactForm, SubscribeForm
# from django.core.paginator import Paginator



class IndexView(View):

	def get(self, *args, **kwargs):
		form = SubscribeForm()
		context = {
			'blogs': Blog.objects.all()[:8],
			'crousal1': Crousal.objects.first(),
			'crousal2': Crousal.objects.filter()[1:2].get(),
			'crousal3': Crousal.objects.filter()[2:3].get(),
			'form': form,
			'user': UserProfile.objects.first()
		}
		return render(self.request, 'index.html', context)

	def post(self, *args, **kwargs):
		form = SubscribeForm(self.request.POST or None)
		if form.is_valid():
			email = form.cleaned_data['email']
			subscriber = Subscriber.objects.create(email=email)
			return redirect('blogApp:index')


class BlogView(ListView):

	model = Blog
	paginate_by = 10
	template_name = 'blog.html'
	context_object_name = 'blogs'
	


class BlogDetail(DetailView):
	model = Blog
	context_object_name = 'blog_details'
	template_name = 'blogdetails.html'
	


class ContactView(View):
	def get(self, *args, **kwargs):
		form = ContactForm()
		context = {
			'form': form
		}
		return render(self.request, 'contact.html', context)

	def post(self, *args, **kwargs):
		form = ContactForm(self.request.POST or None)
		if form.is_valid():
			name = form.cleaned_data['name']
			email = form.cleaned_data['email']
			phone = form.cleaned_data['phone']
			message = form.cleaned_data['message']

			contact = Contact.objects.create(name=name,email=email,phone=phone,message=message)
			# contact.save()


			return redirect('blogApp:index')

blogApp/templates/blog.html
{% load static %}
{% include 'header.html' %}
{% include 'nav.html' %}

    <div class="jumbotron jumbotron-fluid" style="background-image: url('{% static 'blogApp/img/history2.png'%}'); padding-bottom: 10em;">
        <div class="container">
            <!-- <h1 class="display-4">Read the best History blog</h1> -->
            <!-- <p class="lead"><img class="authorImg rounded-circle" src="{{user.avatar.url}}"> -By {{request.user.username}}</p> -->
        </div>
    </div>
    <!-- AllBlog Starts  -->
    <section class="allBlog">
        <div class="container">
            <h3>All Blogs</h3>
            {% for blog in blogs %}
            <div class="row allBlogsPost">
                
                <div class="col-lg-2 col-md-2 col-sm-4 col-4">
                    <img src="{{blog.image.url}}" class="img-fluid">
                </div>
                <div class="col-lg-10 col-md-10 col-sm-8 col-8">
                    <h4>{{blog.title}}</h4>
                    <p class="text-secondary">{{blog.brief|slice:":300"}}...
                        <a href="{{blog.get_absolute_url}}">Read More</a>
                    
                    </p>
                </div>
                
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- AllBlog Ends  -->
    <!-- Pagination Starts  -->
    {% if is_paginated %}
    <section class="paginationBottom">
        <div class="container">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                    {% endif %}

                    {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </section>
    {% endif %}

    {% include 'footer2.html' %}

blogApp/templates/blogdetails.html
{% load static %}
{% include 'header.html' %}
{% include 'nav.html' %}

    <div class="jumbotron jumbotron-fluid" style="background-image: url('{{blog_details.image.url}}'); padding-bottom: 5em;">
        <div class="container">
            <h1 class="display-4 text-white" style="text-align: center;">{{blog_details.title}}</h1>
            <p class="lead text-white" style="text-align: center;">-{{request.user.username}}, {{blog_details.date}}</p>
        </div>
    </div>
    <section>
        <div class="container">
        
            <p>
                {{blog_details.body|safe}}
            </p>
        </div>
    </section>
{% include 'footer2.html' %}

blogApp/templates/contact.html
{% load static %}
{% include 'header.html' %}
{% include 'nav.html' %}
    <!-- Form  -->
    <section class="khanquahcontact">
        <div class="container text-center">
            <h1 class="font-weight-light text-center mt-4 mb-0">Contact Us </h1>
            <p class="text-capitalize text-warning pt-1">We are here to help and answer andy question</p>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-10 offset-lg-2 offset-md-2 offset-1">
                    <form action="" method="post">{% csrf_token %}
                        <div class="form-group">
                            {{form.name}}
                            <!-- <input type="text" class="form-control" id="username" required autocomplete="off"
                                placeholder="Enter your Name"> -->
                            
                        </div>
                        <div class="form-group">
                            {{form.email}}
                            <!-- <input type="email" class="form-control" id="email" required autocomplete="off"
                                placeholder="Enter Email"> -->
                        </div>
                        <div class="form-group">
                            {{form.phone}}
                            <!-- <input type="number" class="form-control" id="mobile" required autocomplete="off"
                                placeholder="Enter Phone Number"> -->
                        </div>
                        <div class="form-group">
                            {{form.message}}
                            <!-- <textarea id="comment" class="form-control" rows="4">Enter your message</textarea> -->
                        </div>
                        <div class="d-flex justify-content-center form-button">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% include 'footer2.html' %}

blogApp/templates/footer.html
    {% load static %}
    <!-- Footer Begins Here  -->
    <section class="footerId">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-6 col-12 justify-content-center text-center footer-div">
                    <h4 class="footerH4">Itihasik Duniya</h4>
                    <p class="text-white">Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Aut amet magni maiores fugiat doloribus at rerum
                    </p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6 col-12 justify-content-center text-center footer-div">
                    <h4 class="footerH4">Navigation links</h4>
                    <li><a href="#latestBlogID">Latest Blogs</a></li>
                    <li><a href="{% url 'blogApp:blogs' %}">All Blogs</a></li>
                    <li><a href="#subscribeblogId">Blogletter</a></li>
                    <li><a href="{% url 'blogApp:contact' %}">Contact Us</a></li>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-12 col-12 justify-content-center text-center footer-div">
                    <h4 class="footerH4">Social Links</h4>
                    <li><a class="fbitext" href="#">Facebook <i class="fa fa-facebook fbi" aria-hidden="true"></i></a>
                    </li>
                    <li><a class="twitext" href="#">Twitter <i class="fa fa-twitter twi" aria-hidden="true"></i></a>
                    </li>
                    <li><a class="insitext" href="#">Instagram <i class="fa fa-instagram insi"
                                aria-hidden="true"></i></a></li>
                    <li> <a class="youtubetext" href="#">Youtube <i class="fa fa-youtube yti"
                                aria-hidden="true"></i></a></li>
                </div>
            </div>
            <div class="mt-4 text-center">
                <p class="text-white">Copyright <i class="fa fa-copyright" aria-hidden="true"></i> <span
                        id="copyrightYear"></span> | All Right Reserved.
                </p>
            </div>
            <div class="scrolltop float-right">
                <i class="fa fa-arrow-up" onclick="topFunction()" id="myBtn"></i>
            </div>
        </div>
    </section>
    <!-- Footer Ends Here  -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="{% static 'blogApp/js/sidebar.js' %}"></script>
    <script src="{% static 'blogApp/js/copyrightYear.js' %}"></script>
    <script src="{% static 'blogApp/js/topFunc.js' %}"></script>
</body>

</html>

blogApp/templates/footer2.html
{% load static %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="{%static 'blogApp/js/sidebar.js' %}"></script>
</body>

</html>

blogApp/templates/header.html
<!doctype html>
<html lang="en">

<head>
    <title>Itihasik Duniya</title>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Internal Style CSS  -->
    <link rel="stylesheet" href="{% static 'blogApp/css/styleindex.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- GOOGLE FONTS  -->
    <link href="https://fonts.googleapis.com/css2?family=Acme&display=swap" rel="stylesheet">
    <!-- Font awesome CSS  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Animate CSS  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css" />
</head>

<body>

blogApp/templates/index.html
    {% load static %}
    {% include 'header.html' %}
    <div class="header" id="topHeader">
        
        <nav class="navbar navbar-expand-sm navbar-dark fixed-top" id="navbarTop">
            <div class="container">
                <a href="{% url 'blogApp:index' %}" class="navbar-brand font-weight-bold text-white">ITIHASIK DUNIA</a>
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navContent">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        <li class="nav-item navCenter">
                            <a href="{% url 'blogApp:blogs' %}" class="nav-link">Blogs</a>
                        </li>
                        <li class="nav-item navCenter">
                            <a href="{% url 'blogApp:contact' %}" class="nav-link">Contact Us</a>
                        </li>
                        <li class="nav-item navCenter">
                            <div id="sidebar" class="sidenav">
                                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                                <h3>About</h3>
                                <div class="mt-2 justify-content-center text-center">
                                    <img class="rounded-circle authorImgIndex" src="{{user.avatar.url}}">
                                </div>
                                <p class="mt-2">I am Anas Nadeem who loves to share information about History.
                                </p>
                                <h3>Social Links</h3>
                                <a class="fbitext" href="#">Facebook <i class="fa fa-facebook fbi"
                                        aria-hidden="true"></i></a>
                                <a class="twitext" href="#">Twitter <i class="fa fa-twitter twi"
                                        aria-hidden="true"></i></a>
                                <a class="insitext" href="#">Instagram <i class="fa fa-instagram insi"
                                        aria-hidden="true"></i></a>
                                <a class="youtubetext" href="#">Youtube <i class="fa fa-youtube yti"
                                        aria-hidden="true"></i></a>
                            </div>
                            <a href="#" class="nav-link"><span onclick="openNav()">About</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <!-- Sidebar Starts Here  -->
<!--         <div id="sidebar" class="sidenav">
            <h3>Welcome</h3>
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <li><a href="blog.html">Blogs</a></li>
            <li><a href="contact.html">Contact US</a></li>
        </div> -->

        <!-- Carousel Starts Here  -->
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active" style="background-image: url('{{crousal1.image.url}}')">
                    <!-- <img class="w-100 imageCarousel" src="../Images/sufi_circuit.jpg" alt="First slide"> -->
                    <div class="carousel-caption d-none d-block">
                        <h5 class="animate__animated animate__bounceInDown">ITIHASIK DUNIYA</h5>
                        <p class="animate__animated animate__bounceInLeft">Beautiful Blogs!!</p>
                        <p class="header-button mt-3 animate__animated animate__bounceInUp"><a href="{% url 'blogApp:blogs' %}">Read Blogs</a>
                        </p>
                    </div>
                </div>
                <div class="carousel-item" style="background-image: url('{{crousal2.image.url}}')">
                    <!-- <img class="w-100 imageCarousel" src="../Images/45.jpg" alt="Second slide"> -->
                    <div class="carousel-caption d-none d-block">
                        <h5 class="animate__animated animate__bounceInLeft">ITIHASIK DUNIYA</h5>
                        <p class="animate__animated animate__bounceInDown">Beautiful Blogs!!</p>
                        <p class="header-button mt-3 animate__animated animate__bounceInRight"><a href="#">Read
                                Blogs</a></p>
                    </div>
                </div>
                <div class="carousel-item" style="background-image: url('{{crousal3.image.url}}')">
                    <!-- <img class="w-100 imageCarousel" src="../Images/3.jpg" alt="Third slide"> -->
                    <div class="carousel-caption d-none d-block">
                        <h5 class="animate__animated animate__bounceInUp">ITIHASIK DUNIYA</h5>
                        <p class="animate__animated animate__bounceInLeft">Beautiful Blogs!!</p>
                        <p class="header-button mt-3 animate__animated animate__bounceInDown"><a href="#">Read Blogs</a>
                        </p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <!-- Carousel Ends Here  -->
    </div>

    <!-- LatestID Starts Here  -->
    <section class="latestBlog" id="latestBlogID">
        <div class="container">
            <h3 class="latestblogtitle">Latest Blog</h3>
            
            <div class="row">
                {% for blog in blogs %}
                <div class="col-lg-6 col-md-6 col-sm-12 col-12 latestBlogCard">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-4">
                            <a href="{{blog.get_absolute_url}}">
                            <img class="img-fluid" src="{{blog.image.url}}">
                            </a>
                        </div>
                        <div class="col-lg-8 col-md-8 col-sm-8 col-8">
                            <h4>{{blog.title}}</h4>
                            <p class="text-secondary">{{blog.brief|slice:":150"}}...
                                <a href="{{blog.get_absolute_url}}">Read More</a>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            
        </div>
    </section>
    <!-- LatestID Ends Here  -->

    <!-- Subscribe to Blog Begins  -->
    <section class="subscribeblog" id="subscribeblogId">
        <div class="container">
            <h3 class="text-center">Subscribe To Our Blog</h3>
            <div class="row">
                <div class="col-lg-8 offset-lg-2 col-12">
                    <form action="" method="post">{% csrf_token %}
                    <div class="input-group blogBar">
                        {{form.email}}
                        <!-- <input type="search" class="form-control searchInput" placeholder="Your Email"> -->

                        <div class="input-group-append">
                            <button type="submit" class="input-group-text subscribeText">Subscribe</button>
                            <!-- <span class="input-group-text subscribeText">Subscribe</span> -->
                        </div>
                    
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Subscribe to Blog Ends  -->

    {% include 'footer.html' %}

blogApp/templates/nav.html
    <!-- Navbar Begins  -->
    <nav class="navbar navbar-dark bg-dark mb-0" id="navbarId">
        <a class="navbar-brand" href="{% url 'blogApp:index' %}"> Itihasik Duniya</a>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <span onclick="openNav()"><i class="fa fa-bars sidebarlogo" aria-hidden="true"></i></span>
            </li>
        </ul>
    </nav>
    <!-- Navbar Ends  -->

        <!-- Sidebar begins  -->
    <div id="sidebar" class="sidenav">
        <h3>Welcome</h3>
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <li><a href="{% url 'blogApp:blogs' %}">Blogs</a></li>
        <li><a href="{% url 'blogApp:contact' %}">Contact US</a></li>
    </div>
    <!-- Sidebar Ends  -->